GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Sic vis pacem para bellum",
    "views": 100
}

###
PUT http://localhost:3000/posts
Content-Type: application/json

{
    "title": "you kenw leos yens mousne",
    "views": 54
}

###
DELETE http://localhost:3000/posts/13
Content-Type: application/json